# Generated by Django 4.2.13 on 2024-07-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Sotiladigan bino')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=25, verbose_name='Familya')),
                ('father_name', models.CharField(max_length=25, verbose_name='otasi ism')),
                ('phone_number', models.CharField(max_length=25, verbose_name="Telefon no'mr")),
                ('mavzu', models.CharField(max_length=60, verbose_name='xullosa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilish vaqti')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_costumer', models.CharField(max_length=70)),
                ('all_contract', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'SMS xabar',
                'verbose_name_plural': 'SMS xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Xonalar soni')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField(verbose_name='maydoni')),
                ('money', models.PositiveBigIntegerField(verbose_name='Binoning narxi')),
                ('month', models.PositiveIntegerField(verbose_name='Qancha oyga olmoqchi')),
                ('advance_payment', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name="Oldindan qancha to'lov")),
                ('monthTomoney', models.CharField(editable=False, max_length=25, verbose_name='Oyiga')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Sotiladigan bino')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costumer', verbose_name="Xaridor To'liq ismi")),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Uy xonalar soni')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
            },
        ),
    ]
