# Generated by Django 4.2.11 on 2024-06-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='month',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
