# Generated by Django 4.2.11 on 2024-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contract_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthTomoney',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
