# Generated by Django 4.2.11 on 2024-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contract_monthtomoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='monthTomoney',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
