# Generated by Django 4.2.13 on 2024-06-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contract_advance_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_costumer', models.CharField(max_length=70)),
                ('all_contract', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterModelOptions(
            name='costumer',
            options={'verbose_name': 'Costumer', 'verbose_name_plural': 'Costumers'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Sotiladigan bino'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='advance_payment',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name="Oldindan qancha to'lov"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='area',
            field=models.PositiveIntegerField(verbose_name='maydoni'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Sotiladigan bino'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costumer', verbose_name="Xaridor To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='money',
            field=models.PositiveBigIntegerField(verbose_name='Binoning narxi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Qancha oyga olmoqchi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='monthTomoney',
            field=models.CharField(editable=False, max_length=25, verbose_name='Oyiga'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='room',
            field=models.PositiveIntegerField(verbose_name='Uy xonalar soni'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilish vaqti'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='father_name',
            field=models.CharField(max_length=25, verbose_name='otasi ism'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Familya'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='mavzu',
            field=models.CharField(max_length=60, verbose_name='xullosa'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name="Telefon no'mr"),
        ),
    ]
