# Generated by Django 4.2.13 on 2024-06-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_admin_alter_costumer_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='SmsMessage',
        ),
    ]
